### PR TITLE
Add docker image for cargo contract

### PR DESCRIPTION
**Pull request by sfffaaa**

### CODE REVIEW

**Comment by sfffaaa** [comment]
The docker images won't contain the node's environment. So if users want to run behavior tests and deploy seed data, users need to install the node/npm in their environment.

**Comment by faisalthaheem** [comment]
@sfffaaa referring to our conversation let's please maintain only one build image for the node/contracts. Can you please ensure the following image is upto date to build the contract? it already builds the node correctly.
https://github.com/peaqnetwork/peaq-network-node-docker-builder

**Comment by sfffaaa** [comment]
> @sfffaaa referring to our conversation let's please maintain only one build image for the node/contracts. Can you please ensure the following image is up to date to build the contract? it already builds the node correctly.

My bad, I've removed the docker image here and moved it to the other project. Therefore, this MR only updates the README.

**Pull request merged**
